import '@/app/globals.css'
import Provider from '@/components/Provider'
import { i18n } from '@/lib/i18n-config'

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: { lang: string }
}) {
  return (
    <html lang="params.lang">
      <body className="h-full bg-white">
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
