import { AdminNav } from "@/components/AdminNav";
import "@/app/globals.css";
import Provider from "@/components/AuthProvider";
import { i18n } from "@/lib/i18n-config";
import {
  HiHome,
  HiDocumentText,
  HiChartPie,
  HiInbox,
  HiShoppingBag,
  HiTable,
  HiUser,
  HiViewBoards,
} from "react-icons/hi";
import { PiChalkboardTeacherFill, PiStudentFill } from "react-icons/pi";
import { BsFillArrowRightCircleFill } from "react-icons/bs";
import SignOutButton from "@/components/SignOutButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <Provider>
      <html lang={params.lang}>
        <body className="flex h-auto min-w-[1024px] justify-center">
          <div className="h-auto w-full bg-gray-200"></div>

          <div className="flex h-fit w-screen min-w-[1024px] max-w-screen-2xl flex-none">
            <header className="sticky top-0 h-screen bg-gray-200">
              <h1 className="py-4 text-center">MSA</h1>
              <SignOutButton />
              <nav>
                <AdminNav lang={params.lang} />
              </nav>
            </header>

            <main className="w-full p-6">{children}</main>
          </div>

          <div className="h-auto w-full"></div>
        </body>
      </html>
    </Provider>
  );
}
