import { AdminNav } from "@/components/AdminNav"
import "@/app/globals.css"
import Provider from "@/components/AuthProvider"
import { i18n } from "@/lib/i18n-config"
import {
  HiHome,
  HiDocumentText,
  HiChartPie,
  HiInbox,
  HiShoppingBag,
  HiTable,
  HiUser,
  HiViewBoards,
} from "react-icons/hi"
import { PiChalkboardTeacherFill, PiStudentFill } from "react-icons/pi"
import { BsFillArrowRightCircleFill } from "react-icons/bs"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  return (
    <Provider>
      <html lang={params.lang}>
        <body className="flex flex-col items-center justify-center min-w-[1024px]">
          <div className="flex max-w-screen-2xl w-screen min-w-[1024px]">
            <header className="border-r h-screen sticky top-0">
              <h1 className="text-center py-4">MSA</h1>
              <nav>
                <AdminNav lang={params.lang} />
              </nav>
            </header>
            {children}
          </div>
        </body>
      </html>
    </Provider>
  )
}
